data_dir = "data/goodreads"
train_data = "train_part_*.parquet"
eval_data = "eval_part_*.parquet"
streaming = true

n_epochs = 10
learning_rate = 3e-4
weight_decay = 1e-4
embed_dim = 16
per_device_train_batch_size = 2048
per_device_eval_batch_size = 2048
mixed_precision = false
seed = 42
