data_dir = "data/goodreads"
train_data = "train_part_*.tfrecord"
eval_data = "eval_part_*.tfrecord"
write_format = "tfrecord"
num_workers = 2

n_epochs = 10
learning_rate = 3e-4
weight_decay = 1e-4
embed_dim = 16
per_device_train_batch_size = 2048
per_device_eval_batch_size = 2048
steps_per_execution = 1
seed = 42

jit_xla = true
use_tpu = false
